---
- name: Deploy Nginx to Kubernetes
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Set Kubernetes Context
      ansible.builtin.import_role:
        name: community.kubernetes.k8s_auth
      vars:
        kubeconfig: "/home/ubuntu/.kube/config.yaml"

    - name: Create Nginx Deployment
      ansible.builtin.import_role:
        name: community.kubernetes.k8s
      vars:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: mynginx
            template:
              metadata:
                labels:
                  app: mynginx
              spec:
                containers:
                  - name: mynginxcontainer
                    image: markdocker77/mccustom-nginx:latest
