---
- name: Deploy Nginx to Kubernetes
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Debug Inventory Hostname
      debug:
        var: inventory_hostname

    - name: Set Kubernetes Context
      kubernetes.core.k8s_auth:
        kubeconfig: "/home/ubuntu/.kube/config"

    - name: Create Nginx Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: mynginx
            template:
              metadata:
                labels:
                  app: mynginx
              spec:
                containers:
                  - name: mynginxcontainer
                    image: markdocker77/mccustom-nginx:latest
