---
- name: Deploy Nginx to Kubernetes
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Specify Python 3 interpreter
  tasks:
    - name: Debug Inventory Hostname
      debug:
        var: inventory_hostname

    - name: Create Nginx Deployment
      kubernetes.core.k8s:
        kubeconfig: "/var/lib/jenkins/workspace/config"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: default  # Specify the namespace here
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: mynginx
            template:
              metadata:
                labels:
                  app: mynginx
              spec:
                containers:
                  - name: mynginxcontainer
                    image: markdocker77/mccustom-nginx:latest
